{"uuid": "2322f4ad-fc6d-4db6-9cc8-4d1aee72db14", "children": ["7dc0ac58-8341-4923-8596-80c377022a2f"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=128.0.6613.113)\nStacktrace:\n\tGetHandleVerifier [0x00007FF72D9AB632+29090]\n\t(No symbol) [0x00007FF72D91E6E9]\n\t(No symbol) [0x00007FF72D7DB1CA]\n\t(No symbol) [0x00007FF72D7D3204]\n\t(No symbol) [0x00007FF72D7C4179]\n\t(No symbol) [0x00007FF72D7C5F42]\n\t(No symbol) [0x00007FF72D7C443F]\n\t(No symbol) [0x00007FF72D7C3CD1]\n\t(No symbol) [0x00007FF72D7C3C10]\n\t(No symbol) [0x00007FF72D7C1AD3]\n\t(No symbol) [0x00007FF72D7C214C]\n\t(No symbol) [0x00007FF72D7DE231]\n\t(No symbol) [0x00007FF72D8773FE]\n\t(No symbol) [0x00007FF72D8566EA]\n\t(No symbol) [0x00007FF72D8765D9]\n\t(No symbol) [0x00007FF72D856493]\n\t(No symbol) [0x00007FF72D8209B1]\n\t(No symbol) [0x00007FF72D821B11]\n\tGetHandleVerifier [0x00007FF72DCC883D+3294125]\n\tGetHandleVerifier [0x00007FF72DD14423+3604371]\n\tGetHandleVerifier [0x00007FF72DD0A2E7+3563095]\n\tGetHandleVerifier [0x00007FF72DA66F16+797318]\n\t(No symbol) [0x00007FF72D92986F]\n\t(No symbol) [0x00007FF72D925454]\n\t(No symbol) [0x00007FF72D9255E0]\n\t(No symbol) [0x00007FF72D914A7F]\n\tBaseThreadInitThunk [0x00007FFFA35D7344+20]\n\tRtlUserThreadStart [0x00007FFFA40E26B1+33]\n\n", "trace": "  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\demowebshop\\Tests\\conftest.py\", line 9, in driver\n    driver.get(\"https://demowebshop.tricentis.com/\")\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 363, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1724913235348, "stop": 1724913239485}], "start": 1724913235348, "stop": 1724913242030}