{"uuid": "022922bf-b93b-43ab-82a7-db9ceecad31f", "children": ["835841aa-033b-4ef2-b594-271321a5a3e7"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=128.0.6613.113)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6AF4EB632+29090]\n\t(No symbol) [0x00007FF6AF45E6E9]\n\t(No symbol) [0x00007FF6AF31B1CA]\n\t(No symbol) [0x00007FF6AF313204]\n\t(No symbol) [0x00007FF6AF304179]\n\t(No symbol) [0x00007FF6AF305F42]\n\t(No symbol) [0x00007FF6AF30443F]\n\t(No symbol) [0x00007FF6AF303CD1]\n\t(No symbol) [0x00007FF6AF303C10]\n\t(No symbol) [0x00007FF6AF301AD3]\n\t(No symbol) [0x00007FF6AF30214C]\n\t(No symbol) [0x00007FF6AF31E231]\n\t(No symbol) [0x00007FF6AF3B73FE]\n\t(No symbol) [0x00007FF6AF3966EA]\n\t(No symbol) [0x00007FF6AF3B65D9]\n\t(No symbol) [0x00007FF6AF396493]\n\t(No symbol) [0x00007FF6AF3609B1]\n\t(No symbol) [0x00007FF6AF361B11]\n\tGetHandleVerifier [0x00007FF6AF80883D+3294125]\n\tGetHandleVerifier [0x00007FF6AF854423+3604371]\n\tGetHandleVerifier [0x00007FF6AF84A2E7+3563095]\n\tGetHandleVerifier [0x00007FF6AF5A6F16+797318]\n\t(No symbol) [0x00007FF6AF46986F]\n\t(No symbol) [0x00007FF6AF465454]\n\t(No symbol) [0x00007FF6AF4655E0]\n\t(No symbol) [0x00007FF6AF454A7F]\n\tBaseThreadInitThunk [0x00007FFFA35D7344+20]\n\tRtlUserThreadStart [0x00007FFFA40E26B1+33]\n\n", "trace": "  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\demowebshop\\Tests\\conftest.py\", line 9, in driver\n    driver.get(\"https://demowebshop.tricentis.com/\")\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 363, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\a2z\\PycharmProjects\\python_framework\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1724931338482, "stop": 1724931349864}], "start": 1724931338482, "stop": 1724931349930}